import {gate,tag} from './setup.ts';
import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {sql,closeDb} from '@aihot/backend/db';
import {getBoss,stopBoss} from '@aihot/backend/jobs/queue';
const asked=gate(),answer=gate();let hits=0;
const http=await import('node:http');
const server=http.createServer(async(_req,res)=>{hits++;asked.open();await answer.promise;
 res.writeHead(200,{'content-type':'text/event-stream'});
 res.end('data: '+JSON.stringify({type:'response.completed',response:{status:'completed',output:[{type:'image_generation_call',status:'completed',result:'aGVsbG8='}]}})+'\n\n');
});
server.listen(0,'127.0.0.1');await once(server,'listening');
const queue='test.image-stop-'+tag(),subject=queue;
let child:ReturnType<typeof spawn>|undefined;
after(async()=>{answer.open();child?.kill('SIGTERM');await new Promise<void>(r=>server.close(()=>r()));await stopBoss();await closeDb();});
test('SIGTERM drains an image receipt and stops polling new jobs',async()=>{
 const boss=await getBoss();await boss.createQueue(queue);
 const script=`
 import {getBoss,stopBoss} from './packages/backend/src/jobs/queue.ts';
 import {requestIllustration} from './packages/backend/src/providers/image.ts';
 import {completeReceipt} from './packages/backend/src/providers/receipts.ts';
 import {sql,closeDb} from './packages/backend/src/db.ts';
 const boss=await getBoss();
 await boss.work(${JSON.stringify(queue)},{pollingIntervalSeconds:0.5},async()=>{const r=await requestIllustration(${JSON.stringify(subject)},'test');await completeReceipt(sql,r.receiptId)});
 process.on('SIGTERM',async()=>{process.send({stopping:true});await stopBoss();await closeDb();process.exit(0)});
 process.send({ready:true});`;
 child=spawn(process.execPath,['--input-type=module','-e',script],{env:{...process.env,MODEL_CALLS_ENABLED:'true',SQUARE_IMAGE_ENABLED:'true',LLM_BASE_URL:`http://127.0.0.1:${(server.address() as import('node:net').AddressInfo).port}`,LLM_API_KEY:'mock',LLM_MODEL:'mock'},stdio:['ignore','pipe','pipe','ipc']});
 let errors='';child.stderr!.on('data',b=>errors+=b);
 const exited=once(child,'exit');
 await Promise.race([once(child,'message'),exited.then(()=>{throw Error(errors)})]);await boss.send(queue,{});await Promise.race([asked.promise,exited.then(()=>{throw Error(errors)})]);
 const stopped=once(child,'message');child.kill('SIGTERM');await stopped;await delay(100);
 await boss.send(queue,{});answer.open();
 const [code]=await exited;assert.equal(code,0,errors);assert.equal(hits,1);
 const [receipt]=await sql`SELECT status FROM receipts WHERE subject=${subject}`;assert.equal(receipt!.status,'completed');
 const pending=await sql`SELECT state FROM pgboss.job WHERE name=${queue} AND state='created'`;assert.equal(pending.length,1);
});
