import {stub,tag} from './setup.ts';
import {readFile,writeFile,unlink} from 'node:fs/promises';
import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {sql,closeDb} from '../packages/backend/src/db.ts';
import {upsertMaterial} from '../packages/backend/src/content/materials.ts';
import {generateSquareDrafts} from '../packages/backend/src/square/drafts.ts';
import {coverKey,renderCover,generatedCover} from '../packages/backend/src/square/cover.ts';
import {publishApprovedDraft} from '../scripts/square/manual.mjs';
const provider=await stub(()=>({choices:[{message:{content:JSON.stringify({title:'协议完成升级',summary:'协议完成升级，详细内容以原始公告为准。',quote:'The upgrade was executed.',occurredAt:null,stage:'executed',conflict:false})}}]}));
Object.assign(process.env,{LLM_BASE_URL:provider.url,LLM_API_KEY:'mock',LLM_MODEL:'manual-mock',SQUARE_PUBLISH_ENABLED:'false'});
let articleId;
after(async()=>{if(articleId)await sql`DELETE FROM square_drafts WHERE article_id=${articleId}`;await provider.close();await closeDb();});
test('manual service flow preserves source time, rejects unapproved and duplicate submissions, records uncertain outcomes',async()=>{
 const source='manual-'+tag(),old=new Date(Date.now()-86400000);
 await sql`INSERT INTO sources(id,name,kind,tier,first_party) VALUES(${source},'Test source','rss','T2',false)`;
 ({articleId}=await upsertMaterial({sourceId:source,url:'https://example.com/'+source,title:'Upgrade',bodyText:'The upgrade was executed. This announcement describes the completed protocol changes with details.',bodyStatus:'ok',publishedAt:old,via:'fetch'}));
 await sql`INSERT INTO publications(article_id,eligible,selected,title,summary,source_id,channel,first_party,url,published_at,discovered_at,timeline_at,sort_at) VALUES(${articleId},true,false,'Upgrade','Upgrade',${source},'news',false,${'https://example.com/'+source},${old},${old},${old},${old})`;
 await generateSquareDrafts({articleId,requestedBy:'test-author'});
 await generateSquareDrafts({articleId,requestedBy:'test-author'});
 const rows=await sql`SELECT * FROM square_drafts WHERE article_id=${articleId}`;assert.equal(rows.length,1);
 const d=rows[0];assert.equal(new Date(d.evidence.publishedAt).getTime(),old.getTime());assert.equal(d.verified_at,null);
 assert.equal((await sql`SELECT selected FROM publications WHERE article_id=${articleId}`)[0].selected,false);
 const key=coverKey(Number(d.id),d.title,d.evidence);
 await renderCover(key+'-ai',d.title,d.evidence.sourceName,d.evidence.publishedAt);
 await sql`UPDATE square_drafts SET cover_status='generated',cover_key=${key} WHERE id=${d.id}`;
 let calls=0;
 const transport={uploadImage:async()=>{calls++;return 'https://example.com/image.png'},publish:async()=>({id:'987654321',shareLink:'https://www.binance.com/square/post/987654321'})};
 const approved=await generatedCover(Number(d.id));
 const approval={id:Number(d.id),hash:d.content_hash,coverHash:approved.hash,operator:'test-author',key:'mock'};
 await assert.rejects(publishApprovedDraft(approval,transport),/stale-source/);
 await assert.rejects(publishApprovedDraft({...approval,hash:'wrong',acceptStale:true},transport),/changed/);
 await sql`UPDATE square_drafts SET evidence=evidence||'{"testOnly":true}'::jsonb WHERE id=${d.id}`;
 await assert.rejects(publishApprovedDraft({...approval,acceptStale:true},transport),/not publishable/);
 await sql`UPDATE square_drafts SET evidence=evidence-'testOnly' WHERE id=${d.id}`;
 assert.equal(calls,0);
 await unlink(approved.file);
 await assert.rejects(publishApprovedDraft({...approval,acceptStale:true},transport),/missing/);
 await writeFile(approved.file,Buffer.from('replaced image'));
 await assert.rejects(publishApprovedDraft({...approval,acceptStale:true},transport),/changed/);
 await assert.rejects(publishApprovedDraft({...approval,coverHash:undefined,acceptStale:true},transport),/cover hash/);
 await writeFile(approved.file,approved.bytes);
 assert.equal(calls,0);
 // Replacing the original during upload cannot change the approved byte buffer sent upstream.
 transport.uploadImage=async(_key,file,bytes)=>{calls++;assert.deepEqual(bytes,approved.bytes);await writeFile(file,Buffer.from('concurrent replacement'));return 'https://example.com/image.png'};
 const r=await publishApprovedDraft({...approval,acceptStale:true},transport);assert.equal(r.id,'987654321');
 assert.equal((await sql`SELECT status FROM square_drafts WHERE id=${d.id}`)[0].status,'published');
 await assert.rejects(publishApprovedDraft({...approval,acceptStale:true},transport));assert.equal(calls,1);
 await writeFile(approved.file,approved.bytes);
 // Reset only this mock row to exercise an ambiguous external response.
 await sql`UPDATE square_drafts SET status='review',platform_id=NULL,platform_url=NULL WHERE id=${d.id}`;
 await assert.rejects(publishApprovedDraft({...approval,acceptStale:true},{...transport,publish:async()=>({id:null})}),/uncertain/);
 assert.equal((await sql`SELECT status FROM square_drafts WHERE id=${d.id}`)[0].status,'unknown');
 await assert.rejects(publishApprovedDraft({...approval,acceptStale:true},transport));assert.equal(calls,2);
 assert.equal(process.env.SQUARE_PUBLISH_ENABLED,'false');
});
