// Crypto 行业配置。内部 itemType 保留上游标识；语义由本行业提示词定义。
export const CATEGORIES = [{key:"tip",label:"方法",section:"研究与方法",guide:"投资研究方法和教程"},{key:"paper",label:"研究",section:"研究与方法",guide:"技术报告和研究论文"},{"key": "protocol", "label": "协议", "section": "协议与网络", "guide": "核心网络升级、故障、客户端发布"}, {"key": "product", "label": "业务", "section": "产品与业务", "guide": "产品上线、付费需求、业务指标"}, {"key": "industry", "label": "宏观", "section": "宏观与政策", "guide": "货币政策、通胀、监管、金融风险及影响市场的能源和地缘事件"}, {"key": "token", "label": "代币", "section": "代币与治理", "guide": "代币发行、解锁、回购、分配与治理阶段"}, {"key": "security", "label": "安全", "section": "安全与偿付", "guide": "攻击、暂停提现、脱锚、偿付问题"}, {"key": "opinion", "label": "研究", "section": "研究与方法", "guide": "原创研究、方法和分析，不能冒充即时事实"}] as const;
export const ITEM_TYPES = ["model_release", "product_launch", "tool_or_prompt", "research_paper", "industry_event", "opinion_analysis", "tutorial_explainer"] as const;
export const CATEGORY_TAGS = ["协议升级", "产品更新", "宏观数据", "政策/监管", "代币机制", "治理进展", "安全事件", "研究分析", "行业动态", "教程/实践", "其他"] as const;
export const TOPIC_TAGS = ["BTC", "ETH", "SOL", "DeFi", "稳定币", "ETF", "解锁", "回购", "AI子网", "利率", "通胀", "流动性", "能源", "原油", "地缘政治", "制裁", "金融风险"] as const;
export const ENTITY_TAGS = ["BTC", "ETH", "SOL", "HYPE", "TAO", "AAVE", "UNI", "LINK", "ENA", "PENDLE", "ONDO", "JUP", "VIRTUAL", "BNB", "XRP", "DOGE", "ADA", "TRX", "SUI", "AVAX", "NEAR", "APT", "ARB", "OP", "TON", "美联储", "SEC"] as const;
export const TAG_SYNONYMS: Readonly<Record<string,string>> = {"监管": "政策/监管", "政策": "政策/监管", "升级": "协议升级", "解锁": "代币机制", "安全": "安全事件", "研究": "研究分析", "观点": "研究分析", "融资": "行业动态", "治理": "治理进展"};
export const CATEGORY_BY_ITEM_TYPE: Readonly<Record<string,string>> = {"model_release": "协议升级", "product_launch": "产品更新", "tool_or_prompt": "代币机制", "research_paper": "研究分析", "industry_event": "行业动态", "opinion_analysis": "研究分析", "tutorial_explainer": "教程/实践"};
export const ENTITIES: Record<string, { name: string; displayTag: string | null; aliases: string[] }> = {"bitcoin": {"name": "BTC", "displayTag": "BTC", "aliases": ["Bitcoin", "BTC", "比特币"]}, "ethereum": {"name": "ETH", "displayTag": "ETH", "aliases": ["Ethereum", "ETH", "以太坊"]}, "solana": {"name": "SOL", "displayTag": "SOL", "aliases": ["Solana", "SOL"]}, "hyperliquid": {"name": "HYPE", "displayTag": "HYPE", "aliases": ["Hyperliquid", "HYPE"]}, "bittensor": {"name": "TAO", "displayTag": "TAO", "aliases": ["Bittensor", "TAO", "Subtensor"]}, "aave": {"name": "AAVE", "displayTag": "AAVE", "aliases": ["Aave", "AAVE"]}, "uniswap": {"name": "UNI", "displayTag": "UNI", "aliases": ["Uniswap", "UNI"]}, "chainlink": {"name": "LINK", "displayTag": "LINK", "aliases": ["Chainlink", "LINK"]}, "ethena": {"name": "ENA", "displayTag": "ENA", "aliases": ["Ethena", "ENA"]}, "pendle": {"name": "PENDLE", "displayTag": "PENDLE", "aliases": ["Pendle"]}, "ondo": {"name": "ONDO", "displayTag": "ONDO", "aliases": ["Ondo"]}, "jupiter": {"name": "JUP", "displayTag": "JUP", "aliases": ["Jupiter", "JUP"]}, "virtuals": {"name": "VIRTUAL", "displayTag": "VIRTUAL", "aliases": ["Virtuals", "VIRTUAL"]}, "fed": {"name": "美联储", "displayTag": "美联储", "aliases": ["Federal Reserve", "FOMC", "美联储"]}, "sec": {"name": "SEC", "displayTag": "SEC", "aliases": ["SEC", "Securities and Exchange Commission"]}, "bnb": {"name": "BNB", "displayTag": "BNB", "aliases": ["BNB Chain", "BNB"]}, "ripple": {"name": "XRP", "displayTag": "XRP", "aliases": ["Ripple", "XRP", "XRPL"]}, "dogecoin": {"name": "DOGE", "displayTag": "DOGE", "aliases": ["Dogecoin", "DOGE"]}, "cardano": {"name": "ADA", "displayTag": "ADA", "aliases": ["Cardano", "ADA"]}, "tron": {"name": "TRX", "displayTag": "TRX", "aliases": ["TRON", "TRX"]}, "sui": {"name": "SUI", "displayTag": "SUI", "aliases": ["Sui", "SUI"]}, "avalanche": {"name": "AVAX", "displayTag": "AVAX", "aliases": ["Avalanche", "AVAX"]}, "near": {"name": "NEAR", "displayTag": "NEAR", "aliases": ["NEAR Protocol", "near.org"]}, "aptos": {"name": "APT", "displayTag": "APT", "aliases": ["Aptos", "APT"]}, "arbitrum": {"name": "ARB", "displayTag": "ARB", "aliases": ["Arbitrum", "ARB"]}, "optimism": {"name": "OP", "displayTag": "OP", "aliases": ["Optimism"]}, "ton": {"name": "TON", "displayTag": "TON", "aliases": ["Toncoin", "The Open Network"]}};
export const IDENTITY_LEXICON: ReadonlyArray<{ id: string; name: string; patterns: RegExp[] }> = Object.entries(ENTITIES).map(([id,e]) => ({id,name:e.name,patterns:e.aliases.map(a => new RegExp(/[a-z]/i.test(a) ? `\\b${a}\\b` : a,"i"))}));
export const PUBLISHER_DOMAINS: ReadonlyArray<{entityId:string;domains:readonly string[]}> = [{"entityId": "bitcoin", "domains": ["bitcoincore.org"]}, {"entityId": "ethereum", "domains": ["ethereum.org"]}, {"entityId": "solana", "domains": ["solana.com"]}, {"entityId": "hyperliquid", "domains": ["hyperliquid.xyz"]}, {"entityId": "bittensor", "domains": ["bittensor.com"]}, {"entityId": "fed", "domains": ["federalreserve.gov"]}, {"entityId": "sec", "domains": ["sec.gov"]}];
export const IDENTITY_CONTEXT_ALIASES: ReadonlyArray<{entityId:string;pattern:RegExp}> = [];
